{
 "title": "Loki v2 Web Analytics Dashboard for NGINX For Image Caching",
 "description": "Loki version 2 showcase using JSON NGINX access logs.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values({job=\"fluentbit\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"fluentbit\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (code) (count_over_time({job=\"fluentbit\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{code}}"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({job=\"fluentbit\"} | json | code >= 500 |__error__=\"\"[$__interval])) / (sum(rate({job=\"fluentbit\"} | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"fluentbit\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"fluentbit\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (forwardedFor) (count_over_time({job=\"fluentbit\"} | json |  __error__=\"\" [5m])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job) (sum_over_time({job=\"fluentbit\"} | json | code=200 | unwrap size |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"fluentbit\"} | json | line_format \"request for {{.path}} with HTTP status: {{.code}} \""
    }
   ]
  },
  {
   "title": "Cached Bytes Sent",
   "type": "stat",
   "description": "These are values that were in HIT or STALE meaning the cached value got returned.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (sum_over_time({job=\"fluentbit\"} | json | cacheStatus = `HIT` or cacheStatus = `STALE` | unwrap size | __error__=`` [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=\"fluentbit\"} | json | unwrap requestTime |  __error__=\"\"  [$__interval]) by (job)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (job) (max_over_time({job=\"fluentbit\"} | json | unwrap requestTime |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (count_over_time({job=\"fluentbit\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{code}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (job) (sum_over_time({job=\"fluentbit\"} | json | code=200 | unwrap size |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by (agent) (count_over_time({job=\"fluentbit\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "topk(20, sum by (referer) (count_over_time({job=\"fluentbit\"} | json |  referer != \"\" and referer !~ \".*?$host.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{referer}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, sum by (forwardedFor) (count_over_time({job=\"fluentbit\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{forwardedFor}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "topk(5,sum by (path) (count_over_time({job=\"fluentbit\"} | json | path != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}