global:
  dnsService: "dns-default"
  # -- configures DNS service namespace
  dnsNamespace: "openshift-dns"

loki:
  # Should authentication be enabled
  auth_enabled: false
  podSecurityContext:
  securityContext:
  query_scheduler:
    max_outstanding_requests_per_tenant: 2048
  storage:
    bucketNames:
      chunks: #<BucketName>
      ruler: #<BucketName>
      admin: #<BucketName>
    type: s3
    s3:
      endpoint: 
      region: na
      secretAccessKey:  #<AWS secret access key>
      accessKeyId:  #<AWS access key ID>
      s3ForcePathStyle: true
      insecure: false

server:
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

  schema_config:
    configs:
    - from: "2022-01-11"
      index:
        period: 24h
        prefix: loki_index_
      store: boltdb-shipper
      object_store: s3
      schema: v12
    - from: "2024-03-28"
      index:
        period: 24h
        prefix: loki_index_
      object_store: s3
      schema: v12
      store: tsdb

#need to test that retenion works before enabling this (otherwise no easy way to tell)
#chunk_store_config:
#  max_look_back_period: 3d

  compactor:
    retention_enabled: true
    shared_store: s3
    compaction_interval: 10m
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

  limits_config:
    retention_period: 2d
  #  retention_period: 400d
    query_timeout: 600s

gateway:
  resources: 
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 50Mi
  replicas: 2
  podSecurityContext:
    runAsUser: 
    runAsGroup: 
    runAsNonRoot: true
    fsGroup: 
  securityContext:
    runAsUser: 
    runAsGroup: 
    runAsNonRoot: true
    fsGroup:

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: false
  lokiCanary:
    enabled: false
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false

rbac:
  # -- If pspEnabled true, a PodSecurityPolicy is created for K8s that use psp.
  pspEnabled: false
  # -- For OpenShift set pspEnabled to 'false' and sccEnabled to 'true' to use the SecurityContextConstraints.
  sccEnabled: false
  # -- Specify PSP annotations
  # Ref: https://kubernetes.io/docs/reference/access-authn-authz/psp-to-pod-security-standards/#podsecuritypolicy-annotations
  pspAnnotations: {}
  # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
  # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
  # -- Whether to install RBAC in the namespace only or cluster-wide. Useful if you want to watch ConfigMap globally.
  namespaced: true

test:
  enabled: false


write:
  resources: 
    limits:
      cpu: 400m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 150Mi
  # -- Number of replicas for the write
  replicas: 2
  autoscaling:
    # -- Enable autoscaling for the write.
    enabled: true
    # -- Minimum autoscaling replicas for the write.
    minReplicas: 2
    # -- Maximum autoscaling replicas for the write.
    maxReplicas: 5
    # -- Target CPU utilisation percentage for the write.
    targetCPUUtilizationPercentage: 100
    # -- Target memory utilization percentage for the write.
  persistence:
    # -- Enable volume claims in pod spec
    volumeClaimsEnabled: true
    # -- Parameters used for the `data` volume when volumeClaimEnabled if false
    dataVolumeParameters:
      emptyDir: {}
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: false
    # -- Size of persistent disk
    size: 1Gi



read:
  resources: 
    limits:
      cpu: 400m
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 250Mi
  # -- Number of replicas for the read
  replicas: 2
  autoscaling:
    # -- Enable autoscaling for the read, this is only used if `queryIndex.enabled: true`
    enabled: true
    # -- Minimum autoscaling replicas for the read
    minReplicas: 2
    # -- Maximum autoscaling replicas for the read
    maxReplicas: 5
    # -- Target CPU utilisation percentage for the read
    targetCPUUtilizationPercentage: 100
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: true
    # -- Size of persistent disk
    size: 1Gi
backend:
  resources: 
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 20m
      memory: 75Mi
  # -- Number of replicas for the backend
  replicas: 2
  persistence:
    # -- Enable volume claims in pod spec
    volumeClaimsEnabled: true
    # -- Parameters used for the `data` volume when volumeClaimEnabled if false
    dataVolumeParameters:
      emptyDir: {}
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: true
    # -- Size of persistent disk
    size: 1Gi #REDUCE IN ACTUAL DEPLOYMENT. BARELY USED

sidecar:
  rules:
    enabled: false

