apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:

spec:
  replicas: {{ .Values.deployment.replicas  }}
  selector:
    matchLabels:
      {{ include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: log-storage
          emptydir: {}
        - name: config-volume
          configMap:
            name: nginx-fluentbit
        - name: cam-images-pvc
          persistentVolumeClaim:
            claimName: cam-images-pvc
      containers:
        - resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu  }}
              memory: {{ .Values.deployment.resources.limits.memory  }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu  }}
              memory: {{ .Values.deployment.resources.requests.memory  }}
          name: {{ include "app.fullname" . }}
          volumeMounts:
            - name: log-storage
              mountPath: /logs
            - name: cam-images-pvc
              mountPath: /app/webcams
#              readOnly: true
          env:
            - name: DRIVEBC_IMAGE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: django
                  key: DRIVEBC_IMAGE_API_BASE_URL
            - name: VERSION
              value: {{ .Values.image.tag  }}
            - name: CACHING_URL
              value: {{ .Values.route.host  }}
            - name: ENVIRONMENT
              value: {{ .Values.environment  }}
          envFrom:
            - secretRef:
                name: temp-auth-secret
          imagePullPolicy: IfNotPresent
          image: >-
            {{ .Values.image.repository  }}:{{ .Values.image.tag  }}
          securityContext:
#            runAsUser: 10001 OPENSHIFT DOESN'T LIKE THIS ID
            runAsGroup: 30001
            seccompProfile:
              type: 'RuntimeDefault'
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
        - name: nginx-fluent-bit-sidecar
          image: 'fluent/fluent-bit:2.2.2'
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 25Mi
          volumeMounts:
            - name: log-storage
              mountPath: /mnt/log
            - name: config-volume
              mountPath: /fluent-bit/etc/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "app.kubernetes.io/instance"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "app.name" . }}
