#!/bin/bash

# Display the value
echo "The value of DRIVEBC_IMAGE_API_BASE_URL in the configmap is" ${DRIVEBC_IMAGE_API_BASE_URL}

# Read the value from the ConfigMap
DRIVEBC_IMAGE_API_BASE_URL=$(cat /path/to/configmap/DRIVEBC_IMAGE_API_BASE_URL)

# Replace $DRIVEBC_BASE_URL in index.html with the ConfigMap value
sed -i "s~\$DRIVEBC_BASE_URL~$DRIVEBC_IMAGE_API_BASE_URL~g" /usr/share/nginx/html/index.html

#display the values
cat /usr/share/nginx/html/index.html

# Start the Nginx server
exec nginx -g 'daemon off;'
