name: Create new Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag Version (incl. prefix; e.g. v1.2.3)
        required: true

jobs:
  tagging:
    if: startsWith(github.ref, 'refs/heads/') == true
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Create a tag
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config commit.gpgsign false

        git tag -a ${{ github.event.inputs.tag }}
        git push origin ${{ github.event.inputs.tag }}

        ${vtag//v}
