#This workflows builds the image, pushes to github packages
name: Build & Test Image to Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

#  push:
#    branches: [ "main" ]   

env:
    IMAGE_NAME: image-caching-gh
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker images
    permissions:
      contents: read
      packages: write
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build nginx image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ vars.CACHING_IMAGE_NAME }}
        tags: latest dev ${{ github.sha }} 
        labels: |
          app=drivebc
        containerfiles: ./compose/caching/Dockerfile

#      This will probably not be needed anymore. Just keeping it for legacy purposes    
#    - name: Push to OpenShift ImageStream
#      uses: redhat-actions/push-to-registry@v2.7
#      with:
#        image: ${{ vars.CACHING_IMAGE_NAME }}
#        registry: ${{ secrets.REGISTRY }}
#        username: ${{ secrets.BUILDER_USERNAME }}
#        password: ${{ secrets.BUILDER_TOKEN }}

    - name: Push to GitHub Packages
      uses: redhat-actions/push-to-registry@v2.7
      with:
         image: ${{ steps.build_image.outputs.image }}
         tags: ${{ steps.build_image.outputs.tags }}
         registry: ${{ env.IMAGE_REGISTRY }}
         username: ${{ env.REGISTRY_USER }}
         password: ${{ env.REGISTRY_PASSWORD }}

  versionUpdate:
    needs: [build]
    runs-on: ubuntu-latest
    name: Update the App Version
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: 80c8d5-dev
        insecure_skip_tls_verify: true

    - name: Update the version
      run: |
        pwd
        ls
        helm upgrade image-caching -f helm/values.yaml --set image.tag="${{ github.sha }}" helm
        #oc set image deployment/image-caching nginx=ghcr.io/wmuldergov/image-caching-gh:${{ github.sha }}
        #oc set env deployment/image-caching --overwrite VERSION=${{ github.sha }}
