#Need to figure out how to handle the two environments in one namespace issue. 
name: Build & Deploy Image Caching Image

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

  push:
    branches: [ "main" ]   

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker images
    environment:
      name: dev
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: build image caching
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ vars.CACHING_IMAGE_NAME }}
        tags: latest ${{ github.sha }}
        labels: |
          app=drivebc
        containerfiles: ./compose/caching/Dockerfile
    - name: push to registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ vars.CACHING_IMAGE_NAME }}
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.BUILDER_USERNAME }}
        password: ${{ secrets.BUILDER_TOKEN }}


  versionUpdate:
    runs-on: ubuntu-latest
    name: Update the App Version
    environment:
      name: dev
    steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: 80c8d5-dev
        insecure_skip_tls_verify: true

    - name: Update the version
      run: |
        oc version
        oc projects
        oc set env deployment/nginx-proxy-caching --overwrite VERSION=2023.11.27.gha1
