#to test copying redis image to own registry

name: Redis TEST

on:
  workflow_dispatch:

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}
    TAGS: latest dev ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker REDIS images
    permissions:
      contents: read
      packages: write
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build redis image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: drivebc-redis
        tags: ${{ env.TAGS }} 
        labels: |
          app=drivebc
        containerfiles: ./compose/redis/Dockerfile

    - name: Push to GitHub Packages
      uses: redhat-actions/push-to-registry@v2.7
      with:
         image: ${{ steps.build_image.outputs.image }}
         tags: ${{ steps.build_image.outputs.tags }}
         registry: ${{ env.IMAGE_REGISTRY }}
         username: ${{ env.REGISTRY_USER }}
         password: ${{ env.REGISTRY_PASSWORD }}
