#This will deploy the selected git tag to openshift.
name: ADD TAG TEST

on: workflow_dispatch

env:
    IMAGE_NAME: image-caching-gh
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}


permissions:
  packages: write
    
jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add latest-uat tag to images
      uses: shrink/actions-docker-registry-tag@v3
      with:
        registry: ghcr.io
        repository: wmuldergov/image-caching-gh
        target: 0.0.8
        tags: |
          latest-uat

