name: Update OpenShift ConfigMap

on:
  workflow_dispatch:

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1

      - name: Log in to OpenShift Cluster
        run: |
          echo oc login --token="${{ secrets.OPENSHIFT_TOKEN }}" --server="${{ secrets.OPENSHIFT_SERVER }}"
          echo oc projects
          echo oc set env deployment/nginx-proxy-caching --overwrite VERSION=2023.11.27.gha
